import ColorFormOption from "./ColorFormOption";

export default function ColorForm({ previewColor, setPreviewColor }) {
  console.log(previewColor);

  return (
    <div className="color-form">
      <ColorFormOption
        color={"black"}
        previewColor={previewColor}
        setPreviewColor={setPreviewColor}
      />
      <ColorFormOption
        color={"darkslategray"}
        previewColor={previewColor}
        setPreviewColor={setPreviewColor}
      />
      <ColorFormOption
        color={"gray"}
        previewColor={previewColor}
        setPreviewColor={setPreviewColor}
      />
      <ColorFormOption
        color={"darkred"}
        previewColor={previewColor}
        setPreviewColor={setPreviewColor}
      />
      <ColorFormOption
        color={"crimson"}
        previewColor={previewColor}
        setPreviewColor={setPreviewColor}
      />
      <ColorFormOption
        color={"orangered"}
        previewColor={previewColor}
        setPreviewColor={setPreviewColor}
      />
      <ColorFormOption
        color={"darkorange"}
        previewColor={previewColor}
        setPreviewColor={setPreviewColor}
      />
      <ColorFormOption
        color={"goldenrod"}
        previewColor={previewColor}
        setPreviewColor={setPreviewColor}
      />
      <ColorFormOption
        color={"darkgreen"}
        previewColor={previewColor}
        setPreviewColor={setPreviewColor}
      />
      <ColorFormOption
        color={"forestgreen"}
        previewColor={previewColor}
        setPreviewColor={setPreviewColor}
      />
      <ColorFormOption
        color={"teal"}
        previewColor={previewColor}
        setPreviewColor={setPreviewColor}
      />
      <ColorFormOption
        color={"navy"}
        previewColor={previewColor}
        setPreviewColor={setPreviewColor}
      />
      <ColorFormOption
        color={"mediumblue"}
        previewColor={previewColor}
        setPreviewColor={setPreviewColor}
      />
      <ColorFormOption
        color={"dodgerblue"}
        previewColor={previewColor}
        setPreviewColor={setPreviewColor}
      />
      <ColorFormOption
        color={"indigo"}
        previewColor={previewColor}
        setPreviewColor={setPreviewColor}
      />
      <ColorFormOption
        color={"purple"}
        previewColor={previewColor}
        setPreviewColor={setPreviewColor}
      />
    </div>
  );
}
